from Feedback import feedback
from RandAns import Answer

def playerGuessVScomputer():
    """
    The player tries to guess the code generated by the computer in 10 tries or less.
    """
    correctAns = Answer() #Random colour code
    print(correctAns) #For testing. Remove before player seriously.
    rounds = 1

    while True:
        guess = input("Enter the letters of your 4 colours((R)ed, (B)lue, (G)reen, (Y)ellow, (P)ink, (W)hite): ")
        guess=guess.upper()
        if len(guess)==4:
            guessTuple=(guess[0],guess[1],guess[2],guess[3])

            if  rounds<11: #Van "<10" naar "<11" omdat je anders maar 9 ronden hebt
                black,white=feedback(guessTuple,correctAns) #The feedback from your guess in compaired to the correct answer
                rounds += 1
                if black == 4: # Four black pins means that all the colours are in the correct position so you win.
                    print("You have won in {} tries".format(rounds))
                    break
                else:
                    print("Your guess {}.\n {} white pins, {} black pins.".format(guessTuple, white, black)) # show feedback to player
                    print("------------------------------------")# maakt de console overzichtelijker.



            else:
                print("GAME OVER!") # When you couldn't guess the code in 10 tries.
                break

        else: #shows that your guess isnt the correct lenght. then start again at the beginning of the while loop.
            print("The lenght of your guess is not 4.\n Guess again with code from 4 letters of the colour code you want to guess.")
